### ISSUE TITLE
Invalid Response 403 for jolocom-did-driver

### ISSUE THREAD

**Issue by BernhardFuchs** [jolocom/jolo-did-method#36]
When resolving the example DID for the Universal Resolver the driver throws following error:

```
(node:46) UnhandledPromiseRejectionWarning: Error: invalid response - 403
    at exports.XMLHttpRequest.request.onreadystatechange (/usr/src/app/node_modules/ethers/utils/web.js:84:29)
    at exports.XMLHttpRequest.dispatchEvent (/usr/src/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/src/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:46) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:46) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Request is:
`https://dev.uniresolver.io/1.0/identifiers/did:jolo:e76fb4b4900e43891f613066b9afca366c6d22f7d87fc9f78a91515be24dfb21`

**Comment by mnzaki** [comment]
This should be fixed soon, but pending publishing to docker hub!

**Comment by chunningham** [comment]
container has been published under `jolocomgmbh/jolocom-did-driver:latest`

**Comment by BernhardFuchs** [comment]
Just pulled the new image and the startup fails with:
```
yarn run v1.13.0
$ yarn prepare && node js/index.js
error Command "prepare" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
